### ISSUE TITLE
FYI: Working for EU accounts.

### ISSUE THREAD

**Issue by koerch** [Nighthawk42/bnet_auth_tool#1]
Hey there,

not technically a problem/issue, just to let you know :-)

Your tool is working for EU accounts, I just extracted my authenticator seed so I can use the ancient `authenticator.jar` I still have lying around to generate tokens on the command line.

Much appreciated!

Best,
Marco

**Comment by Nighthawk42** [comment]
Thanks for the update! It’s great to hear that the tool works well with EU accounts. I'll update the readme. 


Cheers.
